### ISSUE TITLE
Update base when dependency is merged

### ISSUE THREAD

**Issue by ryanhiebert** [ahmed-taj/dep#4] opened 2017-12-25 05:21 UTC
If a pull request has a base that is the branch of a dependency pull request, then watch for that dependency to be merged, and update the dependent's base branch to be the branch that the dependency pull request was merged into.

This would effectively allow for pull request chaining, mentioned at isaacs/github#867. Because the dependent pull request would be made as if it were to the dependency, the diff will be clean.

Because pull requests can only have a base on the same repository / fork as the pull request is on, this inherently requires that pull request chains be all on the same repository (except for the leaf, though that's small consolation).

**Comment by z0al** [comment] 2017-12-26 08:31
Hi @ryanhiebert, thank you for opening this :sparkles:  

Honestly, I had no idea how pull requests chaining, but it sounds interesting to me. I will need some time to figure how things work, then I may give it a shot (if somebody didn't take it already)

Suggestions from anybody are welcome!

**Comment by ryanhiebert** [comment] 2017-12-26 13:37
I was trying to figure it out yesterday, but I haven't been able to get my local clone to even notice the dependencies correctly. Do you have any tips on that? If I can get the current project working, I want PR chaining bad enough that I'm willing to write it.

**Comment by z0al** [comment] 2017-12-26 14:29
What exactly the issue? 

P.S. I'm also available on gitter (username: ahmed-taj , you can reach out there at anytime :)

**Comment by ryanhiebert** [comment] 2017-12-26 15:15
AFA what it takes, I think it's just a call to the UPDATE pull request API to change the base to the base that the dependancy pull request was merged into: https://developer.github.com/v3/pulls/#update-a-pull-request.

**Comment by ryanhiebert** [comment] 2017-12-26 18:24
Would it be better if, instead of being based on explicitly declared dependencies, that it were instead based on just the branches? That way, for this feature, the dependency stuff wouldn't even be needed. It could arguably be made into a separate app entirely, since they would be disjoint features.

**Comment by ryanhiebert** [comment] 2017-12-27 03:31
I don't think it would be wise to base it on branches of pull requests alone. I can imagine a git flow-like situation where you have a development branch that you merge to master on a schedule. If you do that with pull requests you certainly wouldn't want pull requests that are based on your develop branch being automatically being changed to merge into your master branch.

So, using the explicit dependencies still seems like the best idea to me, and thus belongs in this app, I think.

**Comment by z0al** [comment] 2017-12-27 03:49
This feature would probably be turned off by default (for compatibility with existing users) and that can be changed through e.g a configuration in `.github/config.yml`?

**Comment by z0al** [comment] 2017-12-27 12:41
@ryanhiebert correct me if I'm wrong, AFAIK here is what needs to be done (Assuming PR chaining is enabled):

* When a PR e.g. `A` has been (re)opened/edited on branch `M` (as a source branch), we need to look for other open PRs where the target branch is `M` and set `A` as a dependency, right?
* When `A` has been merged into branch e.g `T`, then we need to look for all dependents and change their target branch to be `T`.
* If `A` has been closed, then we change nothing!

**Comment by z0al** [comment] 2017-12-27 12:41
Also, do you think it would be useful to write a comment per dependencies update? e.g: Listing the current dependencies and the cause of change (either user command or PR chaining)

**Comment by ryanhiebert** [comment] 2017-12-27 14:34
> When a PR e.g. A has been (re)opened/edited on branch M (as a source branch), we need to look for other open PRs where the target branch is M and set A as a dependency, right?
>
> Also, do you think it would be useful to write a comment per dependencies update? e.g: Listing the current dependencies and the cause of change (either user command or PR chaining)

No, I don't think we should automatically determine any dependencies based on the branches, at least not for this feature. It could be useful as a separate feature, perhaps, but I think the trade-offs are ones that will need to be considered more fully later, and I'm actually skeptical that it's what we really want at all.

Here's what I want:

* Create pull request A to merge branch `a`  into `master`.
* Create a chained pull request B to merge branch `b` into `a`. Use the normal slash command to set A as a dependency of B.
* When A is merged, notice that (1) B is a dependent of A, (2) B has its base as `a`, which just merged into `master`, so (3) set the base of B to be `master`.

**Comment by z0al** [comment] 2017-12-27 16:06
Oh, OK that makes sense, thanks for the explanation 😄

**Comment by ryanhiebert** [comment] 2017-12-28 13:52
I can imagine there being a case where someone wanted to have a pull request depend on another pull request, but did not want the chaining to happen. For example, consider a git-flow workflow:

* Create a pull request to merge `develop` into `master`. This might happen periodically to make a release.
* Create a second pull request based on `develop`, as most would be in git flow.
* Add a dependency to PR 2 on PR 1, because you decide that you don't want to merge the second pull request into `develop` until after the first PR is merged. In this example, because you don't want this new feature to get into the release.
* Merge PR 1, and be annoyed that it automatically changed the base branch of PR 2 to master, since that's not where you intended for it to go.

I'm not sure if this is an edge case to really worry about or not, but if it is, then the only solution I see is to  make the chaining declarations independent of the dependency declarations. If we're making it possible to depend without chaining, I don't see any reason why we'd want to enforce dependency when we are chaining, though I don't see a case where it would be a problem to do so in practice.

A possible approach would be to make another command, say `/chain #7`, that takes care of the chaining. I think that this likely makes sense as a decent approach. Since it's completely separated from the normal dependencies in this package, though, the argument that it should be a separate installable app resurfaces again.

What do you think, @ahmed-taj ? Should it re-use the dependencies specified already, despite the edge-case? If it should not, should I make this a separate GitHub app, to keep these features separated?

**Comment by z0al** [comment] 2017-12-28 16:49
Well, I never used PRs chaining before or even thought about it when I started this app. 

> Should it re-use the dependencies specified already, despite the edge-case?

I'm not sure yet when do people need to use PRs chaining in the first place. So, if the chaining isn't something people do frequently in a predictable manner, I think your suggested approach (`/chain` command) could work well whether or not the case you mentioned is an edge-case.

> should I make this a separate GitHub app, to keep these features separated?

AFAIK both features could work together perfectly well, but it really depends on how people actually use the features, PRs chaining especially.

**Comment by ryanhiebert** [comment] 2017-12-28 16:54
I use PR chaining in all kinds of bad ways when I am working furiously to implement a bunch of new features, but the review is backlogged a bit, or I'm just delayed in getting things from the first PR fixed. It's a small case, I'll admit, but I do find it to be useful, and I think relatively intuitive once you come across the need.

**Comment by z0al** [comment] 2017-12-28 16:56
So, @ryanhiebert do you think the additional command approach fits your needs?

**Comment by ryanhiebert** [comment] 2017-12-28 17:02
Yes, it does. Given that the chaining feature at this point seems entirely disjoint from the primary feature of this app, though, do you think that it would be best to keep the feature in this app, or put it in a separate app so that people can decide which features they want to use? I guess I'm a bit inclined toward the latter.

**Comment by z0al** [comment] 2017-12-28 17:09
> do you think that it would be best to keep the feature in this app, or put it in a separate app so that people can decide which features they want to use? I guess I'm a bit inclined toward the latter.

You're better aware of the problem we are trying to solve, so, It's totally fine if you think it should be in a separated app, and I would still help you if you need anything!

**Comment by ryanhiebert** [comment] 2017-12-28 18:36
Sounds good! I'll follow your lead and use the project as a way to create a couple of hopefully interesting blog posts ;-) I'm using your blog post to help me get started, so thanks for that. I'll be sure to follow up here with whatever I come up with.

**Comment by z0al** [comment] 2017-12-29 16:24
Hey @ryanhiebert I built a [silly package](https://www.npmjs.com/package/probot-issue-commands) to fix #3 and I think you might find it useful.

It works similar to `probot-commands` in some ways, but it only useful if the command parameters are issue references. An example could be:

```javascript
const { addCommand } = require('probot-issue-commands')

// Type `closes #1, and owner/repo#2`
addCommand(robot, /clos(es|ing)/, (context, issues) => {
	console.log(issues)
	// ['#1','owner/repo#2', ...]
})
```

**Comment by ryanhiebert** [comment] 2017-12-30 13:58
So, I actually don't want to use that because

1. I found that the probot-commands only worked on comments, and didn't work with the PR description. It's possible that I was doing something wrong, but it seems like this package may fall prey to the same issue.
2. I only want it to consider references made in the pull request's description, not follow-up comments. This is because it mirrors the way that GitHub's issue keywords for closing works, and it also allows me to avoid storing issue metadata because I only need to check for those keywords when another pull request is closed (that has a matching head for this PRs base). Also, I don't have to worry about checking permissions, because the only people who could affect the description are the original author and a maintainer, both of which seem perfectly acceptable to me.

Thanks for sharing, though, and if you think those objections would be good to resolve in your package then I'll reconsider using it. I'm just doing it manually right now, and it's really not too bad.

**Comment by z0al** [comment] 2017-12-30 14:17
Yes, my package only meant to be working with issue (PR)  comments


https://github.com/ahmed-taj/probot-issue-commands/blob/29b0d114ad436800d80568dc333be6b2cf05ac5d/index.ts#L44

**Comment by ryanhiebert** [comment] 2017-12-30 15:18
Yeah, I suspect that may not be the most desirable way to do it, and that it would be better to match issue keywords only in the description, which the issue comments seem to not even support, since no comment notification is sent when when the issue is opened with a description.

**Comment by z0al** [comment] 2018-02-08 11:48
Closing this based on the discussion above but feel free to reopen if anything changed ;)

**Closed as completed by z0al** 2018-02-08 11:48 UTC
Labels: enhancement

**Comment by OliverJAsh** [comment] 2019-06-04 13:19
From reading through the thread it seems this wasn't solved. Should we reopen it to track this suggestion?

**Comment by ryanhiebert** [comment] 2019-06-04 13:26
I created https://github.com/apps/chain (repo at https://github.com/ryanhiebert/probot-chain) that watches for closed PRs, and then goes through and updates related PRs with a base of the previous PRs branch. That's been enough for what I wanted. Its running on a free dyno on Heroku right now, so if it gets too much usage we might have to pay for hosting or find another free host, but feel free to try it out!
